services:
    advisingapp.local:
        build:
            context: .
            target: base
            args:
                USER_ID: ${SPIN_USER_ID:-33}
                GROUP_ID: ${SPIN_GROUP_ID:-33}
