#!/command/with-contenv bash

# Exit on error
set -e

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping caching because we could not detect a Laravel install..."
  exit 1
fi

# Symlink storage
if [ "${CREATE_STORAGE_SYMLINK:="true"}" == "true" ]; then
    echo "Creating storage symlink..."
    php "$WEBUSER_HOME/artisan" storage:link --force
    echo "Storage symlink created!"
else
    echo "Skipping storage symlink creation because it was specifically disabled..."
fi

# Modules caching
if [ "${CACHE_MODULES:="false"}" == "true" ]; then
  echo "Caching modules..."
  php "$WEBUSER_HOME/artisan" modules:cache
  echo "Modules cached!"
else
    echo "Skipping module caching because it was specifically disabled..."
fi

# Config caching
if [ "${CACHE_CONFIG:="false"}" == "true" ]; then
  echo "Caching config..."
  php "$WEBUSER_HOME/artisan" config:cache
  echo "Config cached!"
else
    echo "Skipping config caching because it was specifically disabled..."
fi

# Route caching
if [ "${CACHE_ROUTES:="false"}" == "true" ]; then
  echo "Caching routes..."
  php "$WEBUSER_HOME/artisan" route:cache
  echo "Routes cached!"
else
    echo "Skipping route caching because it was specifically disabled..."
fi

# View caching
if [ "${CACHE_VIEWS:="false"}" == "true" ]; then
  echo "Caching views..."
  php "$WEBUSER_HOME/artisan" view:cache
  echo "Views cached!"
else
    echo "Skipping view caching because it was specifically disabled..."
fi

# Event caching
if [ "${CACHE_EVENTS:="false"}" == "true" ]; then
  echo "Caching events..."
  php "$WEBUSER_HOME/artisan" event:cache
  echo "Events cached!"
else
    echo "Skipping event caching because it was specifically disabled..."
fi

# Icon caching
if [ "${CACHE_ICONS:="false"}" == "true" ]; then
  echo "Caching icons..."
  php "$WEBUSER_HOME/artisan" icons:cache
  echo "Icons cached!"
else
    echo "Skipping icon caching because it was specifically disabled..."
fi

# Filament Component caching
if [ "${CACHE_FILAMENT_COMPONENTS:="false"}" == "true" ]; then
  echo "Caching Filament components..."
  php "$WEBUSER_HOME/artisan" filament:cache-components
  echo "Filament components cached!"
else
    echo "Skipping Filament component caching because it was specifically disabled..."
fi

exit 0
