#!/command/with-contenv bash

# Exit on error
set -e

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping Laravel Queue Worker because we could not detect a Laravel install..."
  exit 1
fi

SLEEP_TIME=TEMPLATE_SLEEP

echo "Starting Laravel Queue Worker for queue VAR_QUEUE..."

cd "$WEBUSER_HOME"

USERNAME=$(id -nu "$PUID")

s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" queue:work --sleep=$SLEEP_TIME --queue=VAR_QUEUE