#!/command/with-contenv bash
if [[ $DEBUG_OUTPUT && $DEBUG_OUTPUT == true ]]; then
    # Set NGINX to debug mode
    sed -i 's/^\terror_log.*/\terror_log \/proc\/self\/fd\/2 debug;/' /etc/nginx/nginx.conf

    echo "NGINX is in DEBUG MODE"
fi