<?php

/*
<COPYRIGHT>

    Copyright © 2016-2026, Canyon GBS LLC. All rights reserved.

    Advising App™ is licensed under the Elastic License 2.0. For more details,
    see https://github.com/canyongbs/advisingapp/blob/main/LICENSE.

    Notice:

    - You may not provide the software to third parties as a hosted or managed
      service, where the service provides users with access to any substantial set of
      the features or functionality of the software.
    - You may not move, change, disable, or circumvent the license key functionality
      in the software, and you may not remove or obscure any functionality in the
      software that is protected by the license key.
    - You may not alter, remove, or obscure any licensing, copyright, or other notices
      of the licensor in the software. Any use of the licensor's trademarks is subject
      to applicable law.
    - Canyon GBS LLC respects the intellectual property rights of others and expects the
      same in return. Canyon GBS™ and Advising App™ are registered trademarks of
      Canyon GBS LLC, and we are committed to enforcing and protecting our trademarks
      vigorously.
    - The software solution, including services, infrastructure, and code, is offered as a
      Software as a Service (SaaS) by Canyon GBS LLC.
    - Use of this software implies agreement to the license terms and conditions as stated
      in the Elastic License 2.0.

    For more information or inquiries please visit our website at
    https://www.canyongbs.com or contact us via email at legal@canyongbs.com.

</COPYRIGHT>
*/

// This is a frozen snapshot of all legacy model classes that use HasVersion4Uuids (ordered UUIDv4).
// New models should use HasUuids (UUIDv7) instead.
// Do NOT add new models to this list. Do NOT remove models from this list unless they have been
// intentionally migrated from HasVersion4Uuids to HasUuids (UUIDv7).

return [
    AdvisingApp\Ai\Models\AiAssistant::class,
    AdvisingApp\Ai\Models\AiAssistantConfidentialTeam::class,
    AdvisingApp\Ai\Models\AiAssistantConfidentialUser::class,
    AdvisingApp\Ai\Models\AiAssistantFile::class,
    AdvisingApp\Ai\Models\AiAssistantLink::class,
    AdvisingApp\Ai\Models\AiAssistantUpvote::class,
    AdvisingApp\Ai\Models\AiAssistantUse::class,
    AdvisingApp\Ai\Models\AiMessage::class,
    AdvisingApp\Ai\Models\AiMessageFile::class,
    AdvisingApp\Ai\Models\AiThread::class,
    AdvisingApp\Ai\Models\AiThreadFolder::class,
    AdvisingApp\Ai\Models\ConfidentialPromptTeam::class,
    AdvisingApp\Ai\Models\ConfidentialPromptUser::class,
    AdvisingApp\Ai\Models\DataAdvisor::class,
    AdvisingApp\Ai\Models\LegacyAiMessageLog::class,
    AdvisingApp\Ai\Models\Prompt::class,
    AdvisingApp\Ai\Models\PromptType::class,
    AdvisingApp\Ai\Models\PromptUpvote::class,
    AdvisingApp\Ai\Models\PromptUse::class,
    AdvisingApp\Ai\Models\QnaAdvisor::class,
    AdvisingApp\Ai\Models\QnaAdvisorCategory::class,
    AdvisingApp\Ai\Models\QnaAdvisorFile::class,
    AdvisingApp\Ai\Models\QnaAdvisorLink::class,
    AdvisingApp\Ai\Models\QnaAdvisorMessage::class,
    AdvisingApp\Ai\Models\QnaAdvisorQuestion::class,
    AdvisingApp\Ai\Models\QnaAdvisorThread::class,
    AdvisingApp\Alert\Models\AlertConfiguration::class,
    AdvisingApp\Alert\Models\StudentAlert::class,
    AdvisingApp\Application\Models\Application::class,
    AdvisingApp\Application\Models\ApplicationAuthentication::class,
    AdvisingApp\Application\Models\ApplicationField::class,
    AdvisingApp\Application\Models\ApplicationFieldSubmission::class,
    AdvisingApp\Application\Models\ApplicationStep::class,
    AdvisingApp\Application\Models\ApplicationSubmission::class,
    AdvisingApp\Application\Models\ApplicationSubmissionState::class,
    AdvisingApp\Application\Models\ApplicationSubmissionsChecklistItem::class,
    AdvisingApp\Audit\Models\Audit::class,
    AdvisingApp\Authorization\Models\License::class,
    AdvisingApp\Authorization\Models\OtpLoginCode::class,
    AdvisingApp\Authorization\Models\Permission::class,
    AdvisingApp\Authorization\Models\PermissionGroup::class,
    AdvisingApp\Authorization\Models\Role::class,
    AdvisingApp\BasicNeeds\Models\BasicNeedsCategory::class,
    AdvisingApp\BasicNeeds\Models\BasicNeedsProgram::class,
    AdvisingApp\Campaign\Models\Campaign::class,
    AdvisingApp\Campaign\Models\CampaignAction::class,
    AdvisingApp\Campaign\Models\CampaignActionEducatable::class,
    AdvisingApp\Campaign\Models\CampaignActionEducatableRelated::class,
    AdvisingApp\CareTeam\Models\CareTeam::class,
    AdvisingApp\CareTeam\Models\CareTeamRole::class,
    AdvisingApp\CaseManagement\Models\CaseAssignment::class,
    AdvisingApp\CaseManagement\Models\CaseFeedback::class,
    AdvisingApp\CaseManagement\Models\CaseForm::class,
    AdvisingApp\CaseManagement\Models\CaseFormAuthentication::class,
    AdvisingApp\CaseManagement\Models\CaseFormField::class,
    AdvisingApp\CaseManagement\Models\CaseFormStep::class,
    AdvisingApp\CaseManagement\Models\CaseFormSubmission::class,
    AdvisingApp\CaseManagement\Models\CaseHistory::class,
    AdvisingApp\CaseManagement\Models\CaseModel::class,
    AdvisingApp\CaseManagement\Models\CasePriority::class,
    AdvisingApp\CaseManagement\Models\CaseStatus::class,
    AdvisingApp\CaseManagement\Models\CaseType::class,
    AdvisingApp\CaseManagement\Models\CaseTypeAuditor::class,
    AdvisingApp\CaseManagement\Models\CaseTypeEmailTemplate::class,
    AdvisingApp\CaseManagement\Models\CaseTypeManager::class,
    AdvisingApp\CaseManagement\Models\CaseUpdate::class,
    AdvisingApp\CaseManagement\Models\Sla::class,
    AdvisingApp\Concern\Models\Concern::class,
    AdvisingApp\Concern\Models\ConcernStatus::class,
    AdvisingApp\Consent\Models\ConsentAgreement::class,
    AdvisingApp\Consent\Models\UserConsentAgreement::class,
    AdvisingApp\Division\Models\Division::class,
    AdvisingApp\Engagement\Models\EmailTemplate::class,
    AdvisingApp\Engagement\Models\Engagement::class,
    AdvisingApp\Engagement\Models\EngagementBatch::class,
    AdvisingApp\Engagement\Models\EngagementFile::class,
    AdvisingApp\Engagement\Models\EngagementFileEntities::class,
    AdvisingApp\Engagement\Models\EngagementResponse::class,
    AdvisingApp\Engagement\Models\HolisticEngagement::class,
    AdvisingApp\Engagement\Models\SmsTemplate::class,
    AdvisingApp\Engagement\Models\UnmatchedInboundCommunication::class,
    AdvisingApp\Form\Models\Form::class,
    AdvisingApp\Form\Models\FormAuthentication::class,
    AdvisingApp\Form\Models\FormEmailAutoReply::class,
    AdvisingApp\Form\Models\FormField::class,
    AdvisingApp\Form\Models\FormFieldSubmission::class,
    AdvisingApp\Form\Models\FormStep::class,
    AdvisingApp\Form\Models\FormSubmission::class,
    AdvisingApp\Form\Models\Submissible::class,
    AdvisingApp\Form\Models\SubmissibleAuthentication::class,
    AdvisingApp\Form\Models\SubmissibleField::class,
    AdvisingApp\Form\Models\SubmissibleStep::class,
    AdvisingApp\Form\Models\Submission::class,
    AdvisingApp\Group\Models\Group::class,
    AdvisingApp\Group\Models\GroupSubject::class,
    AdvisingApp\InAppCommunication\Models\TwilioConversation::class,
    AdvisingApp\InAppCommunication\Models\TwilioConversationUser::class,
    AdvisingApp\IntegrationOpenAi\Models\OpenAiResearchRequestVectorStore::class,
    AdvisingApp\IntegrationOpenAi\Models\OpenAiVectorStore::class,
    AdvisingApp\Interaction\Models\Interaction::class,
    AdvisingApp\Interaction\Models\InteractionConfidentialTeam::class,
    AdvisingApp\Interaction\Models\InteractionConfidentialUser::class,
    AdvisingApp\Interaction\Models\InteractionDriver::class,
    AdvisingApp\Interaction\Models\InteractionInitiative::class,
    AdvisingApp\Interaction\Models\InteractionOutcome::class,
    AdvisingApp\Interaction\Models\InteractionRelation::class,
    AdvisingApp\Interaction\Models\InteractionStatus::class,
    AdvisingApp\Interaction\Models\InteractionType::class,
    AdvisingApp\MeetingCenter\Models\BookingGroup::class,
    AdvisingApp\MeetingCenter\Models\BookingGroupAppointment::class,
    AdvisingApp\MeetingCenter\Models\BookingGroupTeam::class,
    AdvisingApp\MeetingCenter\Models\BookingGroupUser::class,
    AdvisingApp\MeetingCenter\Models\Calendar::class,
    AdvisingApp\MeetingCenter\Models\CalendarEvent::class,
    AdvisingApp\MeetingCenter\Models\Event::class,
    AdvisingApp\MeetingCenter\Models\EventAttendee::class,
    AdvisingApp\MeetingCenter\Models\EventRegistrationForm::class,
    AdvisingApp\MeetingCenter\Models\EventRegistrationFormAuthentication::class,
    AdvisingApp\MeetingCenter\Models\EventRegistrationFormField::class,
    AdvisingApp\MeetingCenter\Models\EventRegistrationFormFieldSubmission::class,
    AdvisingApp\MeetingCenter\Models\EventRegistrationFormStep::class,
    AdvisingApp\MeetingCenter\Models\EventRegistrationFormSubmission::class,
    AdvisingApp\MeetingCenter\Models\PersonalBookingPage::class,
    AdvisingApp\Notification\Models\DatabaseMessage::class,
    AdvisingApp\Notification\Models\EmailMessage::class,
    AdvisingApp\Notification\Models\EmailMessageEvent::class,
    AdvisingApp\Notification\Models\SmsMessage::class,
    AdvisingApp\Notification\Models\SmsMessageEvent::class,
    AdvisingApp\Notification\Models\StoredAnonymousNotifiable::class,
    AdvisingApp\Notification\Models\Subscription::class,
    AdvisingApp\Pipeline\Models\EducatablePipelineStage::class,
    AdvisingApp\Pipeline\Models\Pipeline::class,
    AdvisingApp\Pipeline\Models\PipelineStage::class,
    AdvisingApp\Portal\Models\PortalAuthentication::class,
    AdvisingApp\Project\Models\Project::class,
    AdvisingApp\Project\Models\ProjectAuditorTeam::class,
    AdvisingApp\Project\Models\ProjectAuditorUser::class,
    AdvisingApp\Project\Models\ProjectFile::class,
    AdvisingApp\Project\Models\ProjectManagerTeam::class,
    AdvisingApp\Project\Models\ProjectManagerUser::class,
    AdvisingApp\Project\Models\ProjectMilestone::class,
    AdvisingApp\Project\Models\ProjectMilestoneStatus::class,
    AdvisingApp\Prospect\Models\Prospect::class,
    AdvisingApp\Prospect\Models\ProspectAddress::class,
    AdvisingApp\Prospect\Models\ProspectEmailAddress::class,
    AdvisingApp\Prospect\Models\ProspectPhoneNumber::class,
    AdvisingApp\Prospect\Models\ProspectSource::class,
    AdvisingApp\Prospect\Models\ProspectStatus::class,
    AdvisingApp\Report\Models\Report::class,
    AdvisingApp\Report\Models\TrackedEvent::class,
    AdvisingApp\Report\Models\TrackedEventCount::class,
    AdvisingApp\Research\Models\ResearchRequest::class,
    AdvisingApp\Research\Models\ResearchRequestFolder::class,
    AdvisingApp\Research\Models\ResearchRequestParsedFile::class,
    AdvisingApp\Research\Models\ResearchRequestParsedLink::class,
    AdvisingApp\Research\Models\ResearchRequestParsedSearchResults::class,
    AdvisingApp\Research\Models\ResearchRequestQuestion::class,
    AdvisingApp\ResourceHub\Models\ManagerResourceHubArticle::class,
    AdvisingApp\ResourceHub\Models\ResourceHubArticle::class,
    AdvisingApp\ResourceHub\Models\ResourceHubArticleConcern::class,
    AdvisingApp\ResourceHub\Models\ResourceHubArticleUpvote::class,
    AdvisingApp\ResourceHub\Models\ResourceHubArticleView::class,
    AdvisingApp\ResourceHub\Models\ResourceHubCategory::class,
    AdvisingApp\ResourceHub\Models\ResourceHubQuality::class,
    AdvisingApp\ResourceHub\Models\ResourceHubStatus::class,
    AdvisingApp\StudentDataModel\Models\BouncedEmailAddress::class,
    AdvisingApp\StudentDataModel\Models\BouncedPhoneNumber::class,
    AdvisingApp\StudentDataModel\Models\EmailAddressOptInOptOut::class,
    AdvisingApp\StudentDataModel\Models\Enrollment::class,
    AdvisingApp\StudentDataModel\Models\EnrollmentSemester::class,
    AdvisingApp\StudentDataModel\Models\Hold::class,
    AdvisingApp\StudentDataModel\Models\Program::class,
    AdvisingApp\StudentDataModel\Models\SmsOptOutPhoneNumber::class,
    AdvisingApp\StudentDataModel\Models\Student::class,
    AdvisingApp\StudentDataModel\Models\StudentAddress::class,
    AdvisingApp\StudentDataModel\Models\StudentDataImport::class,
    AdvisingApp\StudentDataModel\Models\StudentEmailAddress::class,
    AdvisingApp\StudentDataModel\Models\StudentPhoneNumber::class,
    AdvisingApp\Survey\Models\Survey::class,
    AdvisingApp\Survey\Models\SurveyAuthentication::class,
    AdvisingApp\Survey\Models\SurveyField::class,
    AdvisingApp\Survey\Models\SurveyFieldSubmission::class,
    AdvisingApp\Survey\Models\SurveyStep::class,
    AdvisingApp\Survey\Models\SurveySubmission::class,
    AdvisingApp\Task\Models\ConfidentialTasksProjects::class,
    AdvisingApp\Task\Models\ConfidentialTasksTeams::class,
    AdvisingApp\Task\Models\ConfidentialTasksUsers::class,
    AdvisingApp\Task\Models\Task::class,
    AdvisingApp\Team\Models\Team::class,
    AdvisingApp\Timeline\Models\History::class,
    AdvisingApp\Timeline\Models\Timeline::class,
    AdvisingApp\Webhook\Models\InboundWebhook::class,
    AdvisingApp\Webhook\Models\LandlordInboundWebhook::class,
    AdvisingApp\Workflow\Models\Workflow::class,
    AdvisingApp\Workflow\Models\WorkflowCareTeamDetails::class,
    AdvisingApp\Workflow\Models\WorkflowCaseDetails::class,
    AdvisingApp\Workflow\Models\WorkflowDetails::class,
    AdvisingApp\Workflow\Models\WorkflowEngagementEmailDetails::class,
    AdvisingApp\Workflow\Models\WorkflowEngagementSmsDetails::class,
    AdvisingApp\Workflow\Models\WorkflowEventDetails::class,
    AdvisingApp\Workflow\Models\WorkflowInteractionDetails::class,
    AdvisingApp\Workflow\Models\WorkflowProactiveConcernDetails::class,
    AdvisingApp\Workflow\Models\WorkflowRun::class,
    AdvisingApp\Workflow\Models\WorkflowRunStep::class,
    AdvisingApp\Workflow\Models\WorkflowRunStepRelated::class,
    AdvisingApp\Workflow\Models\WorkflowStep::class,
    AdvisingApp\Workflow\Models\WorkflowSubscriptionDetails::class,
    AdvisingApp\Workflow\Models\WorkflowTagsDetails::class,
    AdvisingApp\Workflow\Models\WorkflowTaskDetails::class,
    AdvisingApp\Workflow\Models\WorkflowTrigger::class,
    App\Models\Authenticatable::class,
    App\Models\BaseModel::class,
    App\Models\Export::class,
    App\Models\FailedImportRow::class,
    App\Models\HealthCheckResultHistoryItem::class,
    App\Models\Import::class,
    App\Models\LandlordSettingsProperty::class,
    App\Models\MonitoredScheduledTask::class,
    App\Models\MonitoredScheduledTaskLogItem::class,
    App\Models\NotificationSetting::class,
    App\Models\NotificationSettingPivot::class,
    App\Models\Pronouns::class,
    App\Models\SettingsProperty::class,
    App\Models\SettingsPropertyWithMedia::class,
    App\Models\SystemUser::class,
    App\Models\Tag::class,
    App\Models\Taggable::class,
    App\Models\Tenant::class,
    App\Models\User::class,
];
