#!/command/with-contenv bash

# Exit on error
set -e

if [ "${BUILD_ASSETS:="true"}" == "true" ]; then
    echo "👉 Building assets..."

    source "$NVM_DIR/nvm.sh"

    php -d variables_order=EGPCS "$WEBUSER_HOME"/artisan app:build-assets
fi
