#!/command/with-contenv bash

# Exit on error
set -e

if [ "${BUILD_CUSTOM_CSS:="false"}" == "true" ]; then
    echo "👉 Building custom CSS..."

    source "$NVM_DIR/nvm.sh"

    php -d variables_order=EGPCS "$WEBUSER_HOME"/artisan app:build-custom-css
fi
