#!/command/with-contenv bash

# Exit on error
set -e

# Check to see if an Artisan file exists and assume it means Laravel is configured.
if [ -f $WEBUSER_HOME/artisan ] && [ ${CACHE_ICONS:="false"} == "true" ]; then
  echo "Caching icons..."

  s6-setuidgid webuser php $WEBUSER_HOME/artisan icons:cache

  echo "Icons cached!"
else
    echo "Skipping icon caching because we could not detect a Laravel install or it was specifically disabled..."
fi

exit 0
