#!/command/with-contenv bash

# Exit on error
set -e

# Check to see if an Artisan file exists and assume it means Laravel is configured.
if [ -f $WEBUSER_HOME/artisan ] && [ ${CLEAR_CACHE:="false"} == "true" ]; then
  echo "Clearing the cache..."
  
  USERNAME=$(id -nu $PUID)

  s6-setuidgid $USERNAME php $WEBUSER_HOME/artisan cache:clear

  echo "Cache Cleared!"
else
    echo "Skipping clearing the cache because we could not detect a Laravel install or it was specifically not enabled..."
fi

exit 0
