#!/command/with-contenv bash

# Exit on error
set -e

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping composer dependency installation because we could not detect a Laravel install..."
  exit 1
fi

if [ "${COMPOSER_INSTALL:="true"}" == "true" ]; then
    if [ -d "$WEBUSER_HOME/vendor" ]; then
        echo "Skipping composer dependency installation because vendor directory already exists. Please remove the vendor directory if you want to reinstall dependencies"
        exit 0
    fi

    echo "👉 Installing composer dependencies..."

    cd "$WEBUSER_HOME"

    USERNAME=$(id -nu "$PUID")

    s6-setuidgid "$USERNAME" composer install --no-interaction --no-progress

    echo "Composer dependencies installed!"
fi

exit 0