#!/command/with-contenv bash

# Exit on error
set -e

# Check to see if an Artisan file exists and assume it means Laravel is configured.
if [ -f $WEBUSER_HOME/artisan ] && [ ${LANDLORD_MIGRATE:="true"} == "true" ]; then
  echo "Running landlord migrations..."

  s6-setuidgid webuser php $WEBUSER_HOME/artisan migrate --database=landlord --path=database/landlord --force --isolated

  echo "Landlord migrations complete!"
else
    echo "Skipping landlord migrations because we could not detect a Laravel install or it was specifically disabled..."
fi

exit 0
