#!/command/with-contenv bash

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping migrations because we could not detect a Laravel install..."
  exit 0
fi

if [ "${LANDLORD_MIGRATE:="true"}" == "true" ]; then
  echo "Dispatching landlord migrations..."

  {
    s6-setuidgid webuser php "$WEBUSER_HOME/artisan" app:dispatch-landlord-migrations \
    && echo "Landlord migrations dispatched!"
  } || {
    echo "Landlord migrations failed to dispatch!"

    # TODO: Do something to send an alert that migrations failed. Currently this will NOT stop the container.
  }
else
    echo "Skipping landlord migrations because it was specifically disabled..."
fi

if [ "${TENANT_MIGRATE:="true"}" == "true" ]; then
  echo "Running tenant migrations..."

  {
    s6-setuidgid webuser php "$WEBUSER_HOME/artisan" tenants:artisan "migrate --database=tenant --force --isolated" \
    && echo "Tenant migrations complete!"
  } || {
    echo "Tenant migrations failed!"

    # TODO: Do something to send an alert that migrations failed. Currently this will NOT stop the container.
  }
else
    echo "Skipping tenant migrations because it was specifically disabled..."
fi

# Queue all migrations and one time operations

# Make landlord and tenant migrations / one time operations run in parallel NOT dependent on each other

# Batch and chain tenant migrations and one time operations

exit 0
