#!/command/with-contenv bash

# Exit on error
set -e

echo "Starting Laravel Octane..."

cd $WEBUSER_HOME

USERNAME=$(id -nu $PUID)

s6-setuidgid root php -d variables_order=EGPCS $WEBUSER_HOME/artisan octane:start --server=swool --host=0.0.0.0 --port=8000
