#!/command/with-contenv bash

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping Sync Schedule Monitor because we could not detect a Laravel install..."
  exit 0
fi

cd "$WEBUSER_HOME" || exit 0

{
echo "Running sync on schedule monitor..." \
&& php "$WEBUSER_HOME/artisan" schedule-monitor:sync \
&& echo "Schedule monitor sync completed!"
} || {
echo "Schedule monitor sync failed!"
}

exit 0
