#!/command/with-contenv bash
response=$(curl -I --location --insecure --silent http://localhost | awk '/^HTTP/{print $2}')

if [[ $response == "302
200" ]] || [[ $response == "302" ]]; then
	exit 0
else
	echo "❌ There seems to be a failure in checking the web server. Here's the response:"
	echo "$response"
	exit 1
fi