#!/command/with-contenv bash

# Exit on error
set -e

cd "$WEBUSER_HOME"

USERNAME=$(id -nu "$PUID")

{
echo "Clearing schedule cache..." \
&& s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" schedule:clear-cache \
&& echo "Schedule cache cleared!"
} || {
echo "Schedule cache clear failed!"
}

echo "Starting Cron..."

touch /etc/crontab /etc/cron.*/*

printenv | grep -xFv -f /etc/environment >> /etc/environment

exec cron -f