#!/command/with-contenv bash

# Exit on error
set -e

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping Laravel Scheduler because we could not detect a Laravel install..."
  exit 1
fi

cd "$WEBUSER_HOME"

USERNAME=$(id -nu "$PUID")

{
echo "Clearing schedule cache..." \
&& s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" schedule:clear-cache \
&& echo "Schedule cache cleared!"
} || {
echo "Schedule cache clear failed!"
}

echo "Starting Laravel Scheduler..."

s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" schedule:work
