#!/command/with-contenv bash

# Exit on error
set -e

if [ ! -f "$WEBUSER_HOME/artisan" ]; then
  echo "Skipping Laravel Scheduler because we could not detect a Laravel install..."
  exit 1
fi

echo "Starting Laravel Scheduler..."

cd "$WEBUSER_HOME"

USERNAME=$(id -nu "$PUID")

s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" schedule:work
