name: Update Yearly Copyright

on:
    workflow_dispatch:
    schedule: # Run every year on January 1st
        - cron: '0 0 1 1 *' # UTC time

jobs:
    update-copyright:
        runs-on: ubuntu-22.04

        timeout-minutes: 10

        steps:
            - name: Checkout `main` Branch
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
              with:
                  token: ${{ secrets.PAT }}

            - name: Set up Ruby
              uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f #1.306.0

            - name: Run copyright script
              run: ruby ./copyright.rb

            - name: Create Pull Request
              # SHA of release v6.1.0
              uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 #8.1.1
              with:
                  token: ${{ secrets.PAT }}
                  commit-message: >
                      chore: update yearly copyright
                  title: Update yearly copyright
                  body: >
                      This is an automated pull request to update the yearly copyright.
                  branch: update-yearly-copyright-
                  branch-suffix: timestamp
                  team-reviewers: canyon-gbs-lead-developers
